# Generated by Django 5.0 on 2024-03-18 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0020_auto_20240309_0616'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Bill of Supply', 'Bill of Supply')], max_length=20)),
                ('profile_name', models.CharField(max_length=100)),
                ('recurring_invoice_number', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('sales_order_number', models.CharField(max_length=100)),
                ('repeat_every', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=200)),
                ('terms_and_conditions', models.TextField()),
                ('document', models.FileField(upload_to='recurring_invoice_documents/')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount_igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.company_payment_term')),
            ],
        ),
    ]
