# Generated by Django 5.0 on 2024-03-18 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0021_recurringinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringinvoice',
            name='repeat_every',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.companyrepeatevery'),
        ),
    ]
